# Configuration File

################# DATA #####################
data:
  data_directory_train: '/home/pavel/fast_drive/Course work/BRATS2021/datasets/train_cropped_for_e3d/train_30_percent_subset'
  data_directory_validate: '/home/pavel/fast_drive/Course work/BRATS2021/datasets/train_cropped_for_e3d/val_30_percent_subset'

  # Following is for 'Testing'
  data_directory_test: '/home/pavel/fast_drive/Course work/BRATS2021/datasets/test (val_subset)'
  save_directory_test: '/media/ssd/Course work/BRATS2021/brats-e1d3/e1d3/inference_results/experiment_6_tta'

  num_classes: 2
  channels: [ 'flair_norm', 't1_norm', 't1ce_norm', 't2_norm' ]
  weight_mask_channel: 'mask'
  # weight matrices determine the center voxels to sample around

  # suffix of ground truth .nii.gz file
  seg_file_suffix: 'seg'

################ NETWORK ###################
network:
  # data and label shape should be = 3 always (volume shape excluding channels)
  # for 2D patches, placement of '1' will specify slicing direction.

  data_shape: [ 96, 96, 96 ]
  label_shape: [ 96, 96, 96 ]

  model_save_directory: '/home/pavel/fast_drive/Course work/BRATS2021/brats-e1d3/e1d3/checkpoints'

  # for testing or resuming training from saved model:
  model_load_directory: '/home/pavel/fast_drive/Course work/BRATS2021/brats-e1d3/e1d3/checkpoints'
  model_load_config: [ '2022-06-20_17.11.24', 'top_1']
  resume_training: True
  log_to_tensorboard: True

############### VALIDATE ###################
validate:
  # Validation done at the end of every epoch
  segments_per_epoch: 75
  batch_size: 4
  augmentation: False
  augmentations_to_do: [ 'flip', 'affine', 'elastic', 'gamma' ]

################# TRAIN ####################
train:
  segments_per_epoch: 150
  batch_size: 2
  augmentation: True
  augmentations_to_do: [ 'flip', 'affine', 'elastic', 'gamma' ]

  epochs: 520

  workers_multithreading: 12

  ### LR ###
  # polynomial decay policy
  initial_learning_rate: 0.001

################## TEST ####################
test:
  batch_size: 4
  test_time_aug: True
  with_label: False
  save_segmentation: True
  segment_overlap: 0.5
